from __future__ import annotations

from .models import RequirementIRV2, SemanticNode


FORMAL_LOWERING_VERSION = "0.2"


def lower_authorization_precondition_tla(
    ir: RequirementIRV2,
    *,
    bounds_json: str = "[]",
) -> str:
    """Produce a non-vacuous TLA+ module for authorization_precondition.

    Predicates are declared as CONSTANT uninterpreted operators so Apalache
    can explore all boolean assignments. The rejects_before obligation maps
    to a real Next transition: no accepted outcome while the premise holds.

    Requirement vs. its negation produce modules with distinct predicate
    declarations and obligation bodies — Apalache can distinguish them.
    """
    root = ir.semantic_ir
    module_name = "Req_" + _safe_name(ir.requirement_id)

    predicates = _premise_predicates(root)
    action_name, state_ref_name = _obligation_components(root)
    const_identifiers = sorted(_scope_identifiers(root))

    pred_decls = "\n".join(
        f"CONSTANT {_pred_name(name)}(_)"
        for name, _ in predicates
    )

    if predicates:
        premise_parts = [
            f"{_pred_name(name)}({', '.join(args)})" if args else _pred_name(name)
            for name, args in predicates
        ]
        premise_expr = " /\\ ".join(premise_parts)
        rejection_cond = premise_expr
        next_steps = (
            f"  \\/ /\\ {rejection_cond}\n"
            f"     /\\ NLRState' = \"rejected\"\n"
            f"  \\/ /\\ ~({rejection_cond})\n"
            f"     /\\ NLRState' = \"accepted\""
        )
    else:
        premise_expr = "TRUE"
        next_steps = "  NLRState' = NLRState"

    # Obligation: when premise holds, the action outcome must not be "accepted"
    obligation_expr = f"{premise_expr} => NLRState /= \"accepted\""

    const_line = f"CONSTANTS {', '.join(const_identifiers)}\n\n" if const_identifiers else ""

    safe_action = _safe_name(action_name)

    return (
        f"---- MODULE {module_name} ----\n"
        f"EXTENDS Naturals, TLC\n\n"
        f"\\* Non-vacuous authorization_precondition lowering.\n"
        f"\\* Generated by nlreq translator {FORMAL_LOWERING_VERSION}; semantics: non_vacuous.\n"
        f"\\* Requirement: {ir.requirement_id}\n"
        f"\\* Temporal bounds: {bounds_json}\n\n"
        f"{const_line}"
        f"{pred_decls}\n\n"
        f"VARIABLE NLRState\n\n"
        f"Init == NLRState = \"idle\"\n\n"
        f"\\* Rejection obligation: rejects({action_name}) before {state_ref_name} when premise holds.\n"
        f"\\* No transition reaches accepted while premise predicates hold.\n"
        f"Step_{safe_action} ==\n{next_steps}\n\n"
        f"Next == Step_{safe_action} \\/ UNCHANGED NLRState\n\n"
        f"Premise == {premise_expr}\n\n"
        f"Obligation == {obligation_expr}\n\n"
        f"RequirementHolds == Premise => Obligation\n\n"
        f"====\n"
    )


def _premise_predicates(root: SemanticNode) -> list[tuple[str, list[str]]]:
    """Return (predicate_name, [identifier_arg_names]) from the premise node."""
    if root.premise is None:
        return []
    premise = root.premise
    nodes = premise.children if premise.kind == "and" else [premise]
    result: list[tuple[str, list[str]]] = []
    for node in nodes:
        if node.kind == "predicate" and node.name:
            args = [str(arg.value) for arg in node.args if arg.kind == "identifier"]
            result.append((node.name, args))
    return result


def _obligation_components(root: SemanticNode) -> tuple[str, str]:
    """Return (action_name, state_ref_name) from the action_obligation node."""
    if root.obligation is None:
        return ("action", "state_change")
    action_node = root.obligation.action
    action_name = (action_node.name or "action") if action_node else "action"
    must = root.obligation.must
    if must is None or must.kind != "before" or len(must.children) < 2:
        return (action_name, "state_change")
    state_node = must.children[1]
    state_ref_name = state_node.name or "state_change"
    return (action_name, state_ref_name)


def _scope_identifiers(root: SemanticNode) -> set[str]:
    """Collect identifier names from scope nodes and premise predicate args."""
    identifiers: set[str] = set()
    for scope_node in root.scope:
        if scope_node.name:
            identifiers.add(scope_node.name)
    if root.premise is not None:
        premise = root.premise
        nodes = premise.children if premise.kind == "and" else [premise]
        for node in nodes:
            for arg in node.args:
                if arg.kind == "identifier":
                    identifiers.add(str(arg.value))
    return identifiers


def _pred_name(name: str) -> str:
    return "Pred_" + _safe_name(name)


def _safe_name(value: str) -> str:
    cleaned = "".join(c if c.isalnum() else "_" for c in value)
    if not cleaned:
        return "Unnamed"
    if cleaned[0].isdigit():
        return "_" + cleaned
    return cleaned
