from __future__ import annotations

from .models import RequirementIRV2, SemanticNode


FORMAL_LOWERING_VERSION = "0.2"


def validate_authorization_precondition_shape(root: SemanticNode) -> list[tuple[str, str]]:
    """Return (kind, reason) pairs for unsupported authorization_precondition shapes.

    Returns an empty list when the shape is fully supported. Callers must refuse
    lowering when the list is non-empty — never silently emit TRUE or fall back
    to defaults.
    """
    problems: list[tuple[str, str]] = []

    if root.premise is None:
        problems.append(("missing_premise", "authorization_precondition requires a premise clause (when ...)"))
        return problems

    premise = root.premise
    nodes = premise.children if premise.kind == "and" else [premise]
    for node in nodes:
        if node.kind != "predicate":
            problems.append((
                node.kind,
                (
                    f"unsupported premise node kind '{node.kind}' in "
                    f"authorization_precondition; only named predicate nodes are supported "
                    f"(e.g. 'when actor is authorized'), not comparisons or membership checks"
                ),
            ))

    if root.obligation is None:
        problems.append(("missing_obligation", "authorization_precondition requires an obligation clause (must ...)"))
    else:
        must = root.obligation.must
        if must is None:
            problems.append(("missing_must", "authorization_precondition obligation requires a must clause"))
        elif must.kind != "before":
            problems.append((
                must.kind,
                (
                    f"authorization_precondition obligation must be 'reject before <state>'; "
                    f"got must node kind '{must.kind}' — unsupported obligation shape"
                ),
            ))

    return problems


def lower_authorization_precondition_tla(
    ir: RequirementIRV2,
    *,
    bounds_json: str = "[]",
) -> str:
    """Produce a non-vacuous TLA+ module for authorization_precondition.

    Predicates are CONSTANT uninterpreted operators so Apalache can explore all
    boolean assignments. The state machine has two executable steps:
    - Step_{action}: guarded on idle; if premise holds → rejected, else → accepted.
    - Step_{state_change}: guarded on accepted; crosses the state_change boundary.
    The obligation is a safety invariant: when the premise holds, state_change is
    unreachable (it can only be reached via accepted, which requires premise false).

    The requirement vs. its negation produce modules whose Obligation bodies differ
    by the predicate name — structurally distinguishable, checker-distinguishable
    only with a live Apalache/TLC binary (PB-4).

    Caller must invoke validate_authorization_precondition_shape first and refuse
    if any problems are returned; this function assumes a supported shape.
    """
    root = ir.semantic_ir
    module_name = "Req_" + _safe_name(ir.requirement_id)

    predicates = _premise_predicates(root)
    action_name, state_ref_name = _obligation_components(root)
    const_identifiers = sorted(_scope_identifiers(root))

    pred_decls = "\n".join(
        f"CONSTANT {_pred_name(name)}(_)"
        for name, _ in predicates
    )

    premise_parts = [
        f"{_pred_name(name)}({', '.join(args)})" if args else _pred_name(name)
        for name, args in predicates
    ]
    premise_expr = " /\\ ".join(premise_parts) if premise_parts else "TRUE"

    const_line = f"CONSTANTS {', '.join(const_identifiers)}\n\n" if const_identifiers else ""

    safe_action = _safe_name(action_name)
    safe_state = _safe_name(state_ref_name)

    # Safety obligation: when premise holds, state_change boundary is unreachable.
    # state_change is only reachable via accepted, which requires premise false.
    obligation_expr = f"{premise_expr} => NLRState /= \"state_changed\""

    return (
        f"---- MODULE {module_name} ----\n"
        f"EXTENDS Naturals, TLC\n\n"
        f"\\* Non-vacuous authorization_precondition lowering.\n"
        f"\\* Generated by nlreq translator {FORMAL_LOWERING_VERSION}; semantics: non_vacuous.\n"
        f"\\* Requirement: {ir.requirement_id}\n"
        f"\\* Temporal bounds: {bounds_json}\n\n"
        f"{const_line}"
        f"{pred_decls}\n\n"
        f"VARIABLE NLRState\n\n"
        f"Init == NLRState = \"idle\"\n\n"
        f"Step_{safe_action} ==\n"
        f"  /\\ NLRState = \"idle\"\n"
        f"  /\\ IF {premise_expr}\n"
        f"     THEN NLRState' = \"rejected\"\n"
        f"     ELSE NLRState' = \"accepted\"\n\n"
        f"Step_{safe_state} ==\n"
        f"  /\\ NLRState = \"accepted\"\n"
        f"  /\\ NLRState' = \"state_changed\"\n\n"
        f"Next == Step_{safe_action} \\/ Step_{safe_state} \\/ UNCHANGED NLRState\n\n"
        f"Premise == {premise_expr}\n\n"
        f"Obligation == {obligation_expr}\n\n"
        f"RequirementHolds == Premise => Obligation\n\n"
        f"====\n"
    )


def _premise_predicates(root: SemanticNode) -> list[tuple[str, list[str]]]:
    """Return (predicate_name, [identifier_arg_names]) from the premise node."""
    if root.premise is None:
        return []
    premise = root.premise
    nodes = premise.children if premise.kind == "and" else [premise]
    result: list[tuple[str, list[str]]] = []
    for node in nodes:
        if node.kind == "predicate" and node.name:
            args = [str(arg.value) for arg in node.args if arg.kind == "identifier"]
            result.append((node.name, args))
    return result


def _obligation_components(root: SemanticNode) -> tuple[str, str]:
    """Return (action_name, state_ref_name) from the action_obligation node."""
    if root.obligation is None:
        return ("action", "state_change")
    action_node = root.obligation.action
    action_name = (action_node.name or "action") if action_node else "action"
    must = root.obligation.must
    if must is None or must.kind != "before" or len(must.children) < 2:
        return (action_name, "state_change")
    state_node = must.children[1]
    state_ref_name = state_node.name or "state_change"
    return (action_name, state_ref_name)


def _scope_identifiers(root: SemanticNode) -> set[str]:
    """Collect identifier names from scope nodes and premise predicate args."""
    identifiers: set[str] = set()
    for scope_node in root.scope:
        if scope_node.name:
            identifiers.add(scope_node.name)
    if root.premise is not None:
        premise = root.premise
        nodes = premise.children if premise.kind == "and" else [premise]
        for node in nodes:
            for arg in node.args:
                if arg.kind == "identifier":
                    identifiers.add(str(arg.value))
    return identifiers


def _pred_name(name: str) -> str:
    return "Pred_" + _safe_name(name)


def _safe_name(value: str) -> str:
    cleaned = "".join(c if c.isalnum() else "_" for c in value)
    if not cleaned:
        return "Unnamed"
    if cleaned[0].isdigit():
        return "_" + cleaned
    return cleaned
